In [1]:
import pandas as pd
import numpy as np

from src.data_cleaning import data_labeling
from src.data_cleaning import feature_engineering
from src.language_processing2 import processing_text
from src.language_processing2 import vectorize_text
from src.modeling import test_model

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import log_loss
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split,KFold

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [2]:
df = pd.read_excel('testing2.xlsx')
df.drop('Unnamed: 0', axis=1, inplace=True)

In [3]:
processing_text(df,'text')

text  spam  \
0      just closed a deal in 27 hours using #AdobeSig...     0   
1      just closed a deal in 2 days using #AdobeSign ...     0   
2      just closed a deal in 2 hours using #AdobeSign...     0   
3      just closed a deal in 26 hours using #AdobeSig...     0   
4      just closed a deal in 6 days using #AdobeSign ...     0   
5      just closed a deal in 35 minutes using #AdobeS...     0   
6      just closed a deal in 3 days using #AdobeSign ...     0   
7      just closed a deal in 58 minutes using #AdobeS...     0   
8      just closed a deal in 7 minutes using #AdobeSi...     0   
9      So apparently IU is catching on and won’t ju...     0   
10     just closed a deal in 27 minutes using #AdobeS...     0   
11     just closed a deal in 21 minutes using #AdobeS...     0   
12     just closed a deal in 4 hours using #AdobeSign...     0   
13     just closed a deal in 28 minutes using #AdobeS...     0   
14     just closed a deal using #AdobeSign https://t....     0   
15     just closed a deal in 25 hours using #AdobeSig...     0   
16     just closed a deal in 3 hours using #AdobeSign...     0   
17     just closed a deal in 8 minutes using #AdobeSi...     0   
18     just closed a deal in 88 minutes using #AdobeS...     0   
19     just closed a deal in 29 hours using #AdobeSig...     0   
20     just closed a deal in 18 minutes using #AdobeS...     0   
21     just closed a deal in 5 minutes using #AdobeSi...     0   
22     just signed an agreement using #AdobeSign http...     0   
23     just closed a deal in 3 minutes using #AdobeSi...     0   
24     just closed a deal in 75 minutes using #AdobeS...     0   
25     just closed a deal in 4 minutes using #AdobeSi...     0   
26     just closed a deal in 12 minutes using #AdobeS...     0   
27     just closed a deal in 73 minutes using #AdobeS...     0   
28     just closed a deal in 3 hours using #AdobeSign...     0   
29     just closed a deal in 5 days using #AdobeSign ...     0   
...                                                  ...   ...   
19976  SignNow rescues your company from the unnecess...     0   
19977  If you send out 1000 docs for HR/Comp signing,...     0   
19978  Extend that last mile with a one-way or two-wa...     0   
19979  SignNow helps put the puzzle pieces together f...     0   
19980  With #SignNow, you are flexible enough to chan...     0   
19981  Do you want a digital interactive &amp; engagi...     0   
19982  @atharkhan @HelloSign @G2Crowd @RightSignature...     0   
19983  Are you looking to make ACH Payments using Str...     0   
19984  5 major benefits of choosing SignNow for #medi...     0   
19985  Do you need to send a document to a group of p...     0   
19986  @beezy It should be back up. It was down for a...     0   
19987  #Didyouknow that you can create a link to put ...     0   
19988  SignNow helps get patient forms signed faster ...     0   
19989  You probably knew that you can save money with...     0   
19990  Need to sign last minute #legal forms? SignNow...     0   
19991  @claaack Hi Mr. November, I apologize. We are ...     0   
19992  and sign the petition as it needs lots &amp; l...     0   
19993  Using an Electronic Signature or E-Signature a...     0   
19994  #LaborDay Weekend yet? Don't let work hold you...     0   
19995  Are you having an event for your office for th...     0   
19996  Summer is fading but the dollars in your bank ...     0   
19997  Do you need to sign documents in person on an ...     0   
19998  Are you stressed about getting a document sign...     0   
19999  Please join in the effort to stop genocide in ...     0   
20000  @Anafa It should be back up. It was down for a...     0   
20001  @signnow Yes, they apologized for the issues b...     0   
20002  SignNow ensures that you cannot be breached by...     0   
20003  @claaack Hi Mr. November, Were you able to get...     0   
20004  Want extra money this #LaborDay weekend withou...     0   
20005  Are you in #HR? Sav

In [4]:
col_name_lst = vectorize_text(df,2000)

In [5]:
df.columns

Index(['text', 'spam', 'spam_marketing', 'spam_hijack', 'spam_corporate',
       'spam_bot', 'spam_known', 'spam_own', 'Docusign', 'onespan',
       ...
       'text-TF-IDF-1990', 'text-TF-IDF-1991', 'text-TF-IDF-1992',
       'text-TF-IDF-1993', 'text-TF-IDF-1994', 'text-TF-IDF-1995',
       'text-TF-IDF-1996', 'text-TF-IDF-1997', 'text-TF-IDF-1998',
       'text-TF-IDF-1999'],
      dtype='object', length=2022)

In [6]:
test_model(df,'spam_corporate',GradientBoostingClassifier,col_name_lst)

Accuracy score of this model is

0.992203118752499

Confusion Matrix of this model is

[[4580    6]
 [  33  383]]

Log-Loss score of this model is

0.039726376946355495

AUC score of this model is

0.9596823736119964


In [22]:
data_training_set = df[:16000]
data_test_set = df[16000:]
y = data_training_set['spam_marketing']
X = data_training_set[['Docusign', 'onespan', 'signnow','adobe sign','listed_count', 'statuses_count','followers_count',
          'favourites_count', 'friends_count','time_float_sin','time_float_cos', 'is_description_none']+col_name_lst]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)
model = RandomForestClassifier()
model.fit(X_train,y_train)

y_predict = model.predict(X_test)
y_pred = model.predict_proba(X_test)
print("Accuracy score of this model is" + "\n")
print(accuracy_score(y_test,y_predict))
print("\n" + "Confusion Matrix of this model is" + "\n")
print(confusion_matrix(y_test,y_predict))
print("\n" + "Log-Loss score of this model is" + "\n")
print(log_loss(y_test,y_pred))
print("\n" + "AUC score of this model is" + "\n")
print(roc_auc_score(y_test,y_predict))

y = data_test_set['spam_marketing']
X = data_test_set[['Docusign', 'onespan', 'signnow','adobe sign','listed_count', 'statuses_count','followers_count',
          'favourites_count', 'friends_count','time_float_sin','time_float_cos', 'is_description_none']+col_name_lst]

y_predict = model.predict(X)
y_pred = model.predict_proba(X)
print("\n"+ "Accuracy score of this model is" + "\n")
print(accuracy_score(y,y_predict))
print("\n" + "Confusion Matrix of this model is" + "\n")
print(confusion_matrix(y,y_predict))
print("\n" + "Log-Loss score of this model is" + "\n")
print(log_loss(y,y_pred))
print("\n" + "AUC score of this model is" + "\n")
print(roc_auc_score(y,y_predict))


/home/daniel/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


Accuracy score of this model is

0.96975

Confusion Matrix of this model is

[[3799   20]
 [ 101   80]]

Log-Loss score of this model is

0.17544198605900624

AUC score of this model is

0.7183759886233271

Accuracy score of this model is

0.8941587618572142

Confusion Matrix of this model is

[[3541   35]
 [ 389   41]]

Log-Loss score of this model is

0.8754517625272655

AUC score of this model is

0.542780682586754


In [25]:
from sklearn.model_selection import train_test_split, KFold


y = data_training_set['spam_marketing']
X = data_training_set[['Docusign', 'onespan', 'signnow','adobe sign','listed_count', 'statuses_count','followers_count',
          'favourites_count', 'friends_count','time_float_sin','time_float_cos', 'is_description_none']+col_name_lst]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

model = RandomForestClassifier()
kf = KFold(n_splits=5, shuffle=True)

ll_performance = []
model_weights = []
#kfold split on X_ (which is X_train of len 110)
for train_index, test_index in kf.split(X):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    model.fit(X_train, y_train)
    y_pred = model.predict_proba(X_test)
    log_ll = log_loss(y_test, y_pred)
    
    ll_performance.append(log_ll)
    #model_weights.append(model.coef_) 

/home/daniel/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [27]:
np.mean(ll_performance)

0.21568372295246402

In [13]:
model = MultinomialNB()
df3 = df

X = text_tfidf_matrix
y = df3['spam_bot']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

model.fit(X_train,y_train)

y_predict = model.predict(X_test)
y_pred = model.predict_proba(X_test)
print("Accuracy score of this model is" + "\n")
print(accuracy_score(y_test,y_predict))
print("\n" + "Confusion Matrix of this model is" + "\n")
print(confusion_matrix(y_test,y_predict))
print("\n" + "Log-Loss score of this model is" + "\n")
print(log_loss(y_test,y_pred))
print("\n" + "AUC score of this model is" + "\n")
print(roc_auc_score(y_test,y_predict))

Accuracy score of this model is

0.9872051179528188

Confusion Matrix of this model is

[[1955   57]
 [   7 2983]]

Log-Loss score of this model is

0.02362389674075928

AUC score of this model is

0.9846644214977692


In [15]:
model = MultinomialNB()
df3 = df

X = text_tfidf_matrix
y = df3['spam_hijack']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

model.fit(X_train,y_train)

y_predict = model.predict(X_test)
y_pred = model.predict_proba(X_test)
print("Accuracy score of this model is" + "\n")
print(accuracy_score(y_test,y_predict))
print("\n" + "Confusion Matrix of this model is" + "\n")
print(confusion_matrix(y_test,y_predict))
print("\n" + "Log-Loss score of this model is" + "\n")
print(log_loss(y_test,y_pred))
print("\n" + "AUC score of this model is" + "\n")
print(roc_auc_score(y_test,y_predict))

Accuracy score of this model is

0.8486605357856857

Confusion Matrix of this model is

[[3243  666]
 [  91 1002]]

Log-Loss score of this model is

0.26606907252058337

AUC score of this model is

0.8731834270832529


In [18]:
data_training_set = df3[:16000]
data_test_set = df3[16000:]
y = data_training_set['spam_marketing']
X = data_training_set[['Docusign', 'onespan', 'signnow','adobe sign','listed_count', 'statuses_count','followers_count',
          'favourites_count', 'friends_count','time_float_sin','time_float_cos', 'is_description_none']+col_name_lst]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)
model = GradientBoostingClassifier()
model.fit(X_train,y_train)

y_predict = model.predict(X_test)
y_pred = model.predict_proba(X_test)
print("Accuracy score of this model is" + "\n")
print(accuracy_score(y_test,y_predict))
print("\n" + "Confusion Matrix of this model is" + "\n")
print(confusion_matrix(y_test,y_predict))
print("\n" + "Log-Loss score of this model is" + "\n")
print(log_loss(y_test,y_pred))
print("\n" + "AUC score of this model is" + "\n")
print(roc_auc_score(y_test,y_predict))

Accuracy score of this model is

0.96425

Confusion Matrix of this model is

[[3802   22]
 [ 121   55]]

Log-Loss score of this model is

0.09594199545494962

AUC score of this model is

0.6533734309623431


In [19]:
from src.language_processing2 import processing_text

ModuleNotFoundError: No module named 'src.language_processing2'