In [1]:
import pandas as pd
import numpy as np

from src.language_processing2 import processing_text
from src.language_processing2 import vectorize_text
from src.language_processing2 import vectorize_desc
from src.modeling import test_model
from src.modeling import test_model2
from src.modeling import test_model3
from src.modeling import test_model4

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import log_loss
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split,KFold

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [2]:
def test_model6(data,column,TFIDF_column,estimators,dep):
    data2 = data.sample(frac=1)
    data2_training = data2[:16000]
    data2_testing = data2[16000:]
    y = data2_training[column]
    X = data2_training[['Docusign', 'onespan', 'signnow','adobe sign','listed_count', 'statuses_count','followers_count','favourites_count', 'friends_count','time_float_sin','time_float_cos', 'is_description_none'] + TFIDF_column]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)
    model = GradientBoostingClassifier(subsample=0.5, learning_rate=0.1, n_estimators=estimators,max_depth=dep)
    kf = KFold(n_splits=5, shuffle=True)

    ll_performance = []
    auc_performance = []
    acc_performance = []
#kfold split on X_ (which is X_train of len 110)
    for train_index, test_index in kf.split(X):
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train, y_train)
        y_predict = model.predict(X_test)
        y_pred = model.predict_proba(X_test)
        log_ll = log_loss(y_test, y_pred)
        ll_performance.append(log_ll)
        auc = roc_auc_score(y_test,y_predict)
        auc_performance.append(auc)
        acc = accuracy_score(y_test,y_predict)
        acc_performance.append(acc)
        
        
    print("\n" + "Score summary for initial test (first 80% of data)" + "\n")
    print("\n" + "Accuracy score of this model is" + "\n")
    print(np.mean(acc_performance))
    print("\n" + "Log-Loss score of this model is" + "\n")
    print(np.mean(ll_performance))
    print("\n" + "AUC score of this model is" + "\n")
    print(np.mean(auc_performance))
    print("\n")

    y = data2_testing[column]
    X = data2_testing[['Docusign', 'onespan', 'signnow','adobe sign','listed_count', 'statuses_count','followers_count','favourites_count', 'friends_count','time_float_sin','time_float_cos', 'is_description_none'] + TFIDF_column]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)
    #model = model()
    kf = KFold(n_splits=5, shuffle=True)

    ll_performance = []
    auc_performance = []
    acc_performance = []
#kfold split on X_ (which is X_train of len 110)
    for train_index, test_index in kf.split(X):
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train, y_train)
        y_predict = model.predict(X_test)
        y_pred = model.predict_proba(X_test)
        log_ll = log_loss(y_test, y_pred)
        ll_performance.append(log_ll)
        auc = roc_auc_score(y_test,y_predict)
        auc_performance.append(auc)
        acc = accuracy_score(y_test,y_predict)
        acc_performance.append(acc)
        
        
    print("\n" + "Score summary for final test (last 20% of data)" + "\n")
    print("\n" + "Accuracy score of this model is" + "\n")
    print(np.mean(acc_performance))
    print("\n" + "Log-Loss score of this model is" + "\n")
    print(np.mean(ll_performance))
    print("\n" + "AUC score of this model is" + "\n")
    print(np.mean(auc_performance))
    #print("\n" + "Coefficients of this model are" + "\n")
    #print(model.coef_)
    #print("\n" + "Most effective predictor was" + "\n")
    return None

In [4]:
estimator_candidate = range(300,900,200)
depth_candidate = range(2,8,2)

In [ ]:
for d in depth_candidate:
    for e in estimator_candidate:
        df = pd.read_excel('testing2.xlsx')
        df.drop('Unnamed: 0', axis=1, inplace=True)
        processing_text(df,'text')
        col_name_lst1 = vectorize_text(df,700)
        processing_text(df,'description')
        col_name_lst2 = vectorize_desc(df,700)
        print("estimator is " + str(e) + "\n depth is " + str(d))
        test_model6(df,'spam_marketing',col_name_lst1+col_name_lst2,e,d)

estimator is 300
 depth is 2

Score summary for initial test (first 80% of data)


Accuracy score of this model is

0.952

Log-Loss score of this model is

0.12719035478532043

AUC score of this model is

0.6819651544482398



Score summary for final test (last 20% of data)


Accuracy score of this model is

0.9455839178582881

Log-Loss score of this model is

0.15125087219433717

AUC score of this model is

0.6248348297018851
estimator is 500
 depth is 2

Score summary for initial test (first 80% of data)


Accuracy score of this model is

0.9531875000000001

Log-Loss score of this model is

0.12665184178680847

AUC score of this model is

0.6937526685332067



Score summary for final test (last 20% of data)


Accuracy score of this model is

0.9478304862064564

Log-Loss score of this model is

0.15632027320031647

AUC score of this model is

0.6827370131896009
estimator is 700
 depth is 2

Score summary for initial test (first 80% of data)


Accuracy score of this model is

0.9535

L

In [3]:
depth_candidate = list(range(2,8,2))
print(depth_candidate)

[2, 4, 6]


In [4]:
df = pd.read_excel('testing2.xlsx')
df.drop('Unnamed: 0', axis=1, inplace=True)
processing_text(df,'text')
col_name_lst1 = vectorize_text(df,700)
processing_text(df,'description')
col_name_lst2 = vectorize_desc(df,700)
test_model6(df,'spam_marketing',col_name_lst1+col_name_lst2,500,2)


Score summary for initial test (first 80% of data)


Accuracy score of this model is

0.9541875

Log-Loss score of this model is

0.12411044494842816

AUC score of this model is

0.6935869807570457



Score summary for final test (last 20% of data)


Accuracy score of this model is

0.9458298697700194

Log-Loss score of this model is

0.15094225130900585

AUC score of this model is

0.6803877176686943


In [5]:
model.feature_importance_

NameError: name 'model' is not defined

In [60]:
def test_model4(data,column,TFIDF_column):
    data2 = data.sample(frac=1)
    data2_training = data2[:16000]
    data2_testing = data2[16000:]
    y = data2_training[column]
    X = data2_training[['Docusign', 'onespan', 'signnow','adobe sign','listed_count', 'statuses_count','followers_count','favourites_count', 'friends_count','time_float_sin','time_float_cos', 'is_description_none'] + TFIDF_column]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)
    model = RandomForestClassifier(n_estimators=500)
    kf = KFold(n_splits=5, shuffle=True)

    ll_performance = []
    auc_performance = []
    acc_performance = []
#kfold split on X_ (which is X_train of len 110)
    for train_index, test_index in kf.split(X):
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train, y_train)
        y_predict = model.predict(X_test)
        y_pred = model.predict_proba(X_test)
        log_ll = log_loss(y_test, y_pred)
        ll_performance.append(log_ll)
        auc = roc_auc_score(y_test,y_predict)
        auc_performance.append(auc)
        acc = accuracy_score(y_test,y_predict)
        acc_performance.append(acc)
        
        
    print("\n" + "Score summary for initial test (first 80% of data)" + "\n")
    print("\n" + "Accuracy score of this model is" + "\n")
    print(np.mean(acc_performance))
    print("\n" + "Log-Loss score of this model is" + "\n")
    print(np.mean(ll_performance))
    print("\n" + "AUC score of this model is" + "\n")
    print(np.mean(auc_performance))
    print("\n")

    y = data2_testing[column]
    X = data2_testing[['Docusign', 'onespan', 'signnow','adobe sign','listed_count', 'statuses_count','followers_count','favourites_count', 'friends_count','time_float_sin','time_float_cos', 'is_description_none'] + TFIDF_column]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)
    #model = model()
    kf = KFold(n_splits=5, shuffle=True)

    ll_performance = []
    auc_performance = []
    acc_performance = []
#kfold split on X_ (which is X_train of len 110)
    for train_index, test_index in kf.split(X):
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train, y_train)
        y_predict = model.predict(X_test)
        y_pred = model.predict_proba(X_test)
        log_ll = log_loss(y_test, y_pred)
        ll_performance.append(log_ll)
        auc = roc_auc_score(y_test,y_predict)
        auc_performance.append(auc)
        acc = accuracy_score(y_test,y_predict)
        acc_performance.append(acc)
        
        
    print("\n" + "Score summary for final test (last 20% of data)" + "\n")
    print("\n" + "Accuracy score of this model is" + "\n")
    print(np.mean(acc_performance))
    print("\n" + "Log-Loss score of this model is" + "\n")
    print(np.mean(ll_performance))
    print("\n" + "AUC score of this model is" + "\n")
    print(np.mean(auc_performance))
    #print("\n" + "Coefficients of this model are" + "\n")
    #print(model.coef_)
    #print("\n" + "Most effective predictor was" + "\n")
    return model

In [7]:
df = pd.read_excel('testing2.xlsx')
df.drop('Unnamed: 0', axis=1, inplace=True)
processing_text(df,'text')
col_name_lst1 = vectorize_text(df,700)
processing_text(df,'description')
col_name_lst2 = vectorize_desc(df,700)
model = test_model4(df,'spam_marketing',col_name_lst1+col_name_lst2)


Score summary for initial test (first 80% of data)


Accuracy score of this model is

0.9563124999999999

Log-Loss score of this model is

0.11041367908153166

AUC score of this model is

0.6952529752683233



Score summary for final test (last 20% of data)


Accuracy score of this model is

0.9558152060547757

Log-Loss score of this model is

0.12212558008827554

AUC score of this model is

0.65464789168158


In [10]:
fim = model.feature_importances_

In [16]:
fim[:50]

array([3.56645703e-03, 1.45130761e-03, 9.59920976e-04, 6.94925339e-03,
       1.05959724e-02, 1.18035119e-02, 1.05156765e-02, 1.27527707e-02,
       1.15527283e-02, 1.35104589e-02, 1.51078245e-02, 9.49119877e-04,
       6.99455081e-04, 8.74897364e-05, 5.44590191e-04, 2.03124648e-03,
       4.39128715e-05, 1.33529375e-08, 2.76992769e-05, 5.98722804e-05,
       1.86765433e-04, 0.00000000e+00, 9.26395252e-08, 2.14038031e-08,
       1.22886949e-03, 1.08111163e-05, 2.32860226e-04, 1.15636487e-03,
       1.69659799e-04, 1.06611276e-05, 3.03120886e-05, 9.95236356e-07,
       2.99884197e-05, 1.77041145e-04, 1.51435961e-09, 3.13364510e-06,
       7.04989344e-06, 9.04059576e-06, 2.42741786e-04, 1.64483843e-03,
       0.00000000e+00, 1.14128066e-03, 7.12930093e-05, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 4.77789940e-04])

In [22]:
columns = ['Docusign', 'onespan', 'signnow','adobe sign','listed_count', 'statuses_count','followers_count','favourites_count', 'friends_count','time_float_sin','time_float_cos', 'is_description_none'] + col_name_lst1+col_name_lst2

In [ ]:
fig,ax = plt.subplots()
ax.plot(fim,columns)

In [30]:
import matplotlib.pyplot as plt

In [25]:
plt.

AttributeError: module 'matplotlib' has no attribute 'plot'

In [37]:
df = pd.read_excel('testing2.xlsx')
df.drop('Unnamed: 0', axis=1, inplace=True)
processing_text(df,'text')
col_name_lst1 = vectorize_text(df,700)
processing_text(df,'description')
col_name_lst2 = vectorize_desc(df,700)
test_model3(df,'spam_marketing',LogisticRegression,col_name_lst1+col_name_lst2)

/home/daniel/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/daniel/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/daniel/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/daniel/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/daniel/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs


Score summary for initial test (first 80% of data)


Accuracy score of this model is

0.94025

Log-Loss score of this model is

0.1936155587980399

AUC score of this model is

0.5018150223625382




/home/daniel/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/daniel/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/daniel/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/daniel/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/daniel/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs


Score summary for final test (last 20% of data)


Accuracy score of this model is

0.9405889147294062

Log-Loss score of this model is

0.18812077242576453

AUC score of this model is

0.5020416379112032


In [38]:
df = pd.read_excel('testing2.xlsx')
df.drop('Unnamed: 0', axis=1, inplace=True)
processing_text(df,'text')
col_name_lst1 = vectorize_text(df,700)
processing_text(df,'description')
col_name_lst2 = vectorize_desc(df,700)
model = test_model4(df,'spam_marketing',[col_name_lst1+col_name_lst2])


Score summary for initial test (first 80% of data)


Accuracy score of this model is

0.9492499999999999

Log-Loss score of this model is

0.1516921893055328

AUC score of this model is

0.6564082560931521



Score summary for final test (last 20% of data)


Accuracy score of this model is

0.9465804900981005

Log-Loss score of this model is

0.1566818514874027

AUC score of this model is

0.6068767363139868


In [40]:
def test_model4_notext(data,column):
    data2 = data.sample(frac=1)
    data2_training = data2[:16000]
    data2_testing = data2[16000:]
    y = data2_training[column]
    X = data2_training[['Docusign', 'onespan', 'signnow','adobe sign','listed_count', 'statuses_count','followers_count','favourites_count', 'friends_count','time_float_sin','time_float_cos', 'is_description_none']]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)
    model = RandomForestClassifier(n_estimators=500)
    kf = KFold(n_splits=5, shuffle=True)

    ll_performance = []
    auc_performance = []
    acc_performance = []
#kfold split on X_ (which is X_train of len 110)
    for train_index, test_index in kf.split(X):
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train, y_train)
        y_predict = model.predict(X_test)
        y_pred = model.predict_proba(X_test)
        log_ll = log_loss(y_test, y_pred)
        ll_performance.append(log_ll)
        auc = roc_auc_score(y_test,y_predict)
        auc_performance.append(auc)
        acc = accuracy_score(y_test,y_predict)
        acc_performance.append(acc)
        
        
    print("\n" + "Score summary for initial test (first 80% of data)" + "\n")
    print("\n" + "Accuracy score of this model is" + "\n")
    print(np.mean(acc_performance))
    print("\n" + "Log-Loss score of this model is" + "\n")
    print(np.mean(ll_performance))
    print("\n" + "AUC score of this model is" + "\n")
    print(np.mean(auc_performance))
    print("\n")

    y = data2_testing[column]
    X = data2_testing[['Docusign', 'onespan', 'signnow','adobe sign','listed_count', 'statuses_count','followers_count','favourites_count', 'friends_count','time_float_sin','time_float_cos', 'is_description_none']]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)
    #model = model()
    kf = KFold(n_splits=5, shuffle=True)

    ll_performance = []
    auc_performance = []
    acc_performance = []
#kfold split on X_ (which is X_train of len 110)
    for train_index, test_index in kf.split(X):
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train, y_train)
        y_predict = model.predict(X_test)
        y_pred = model.predict_proba(X_test)
        log_ll = log_loss(y_test, y_pred)
        ll_performance.append(log_ll)
        auc = roc_auc_score(y_test,y_predict)
        auc_performance.append(auc)
        acc = accuracy_score(y_test,y_predict)
        acc_performance.append(acc)
        
        
    print("\n" + "Score summary for final test (last 20% of data)" + "\n")
    print("\n" + "Accuracy score of this model is" + "\n")
    print(np.mean(acc_performance))
    print("\n" + "Log-Loss score of this model is" + "\n")
    print(np.mean(ll_performance))
    print("\n" + "AUC score of this model is" + "\n")
    print(np.mean(auc_performance))
    #print("\n" + "Coefficients of this model are" + "\n")
    #print(model.coef_)
    #print("\n" + "Most effective predictor was" + "\n")
    return None


In [41]:
df = pd.read_excel('testing2.xlsx')
df.drop('Unnamed: 0', axis=1, inplace=True)
model = test_model4_notext(df,'spam_marketing')


Score summary for initial test (first 80% of data)


Accuracy score of this model is

0.9489375000000001

Log-Loss score of this model is

0.1515473389897413

AUC score of this model is

0.6561029827990346



Score summary for final test (last 20% of data)


Accuracy score of this model is

0.9485773705561316

Log-Loss score of this model is

0.1623562428468641

AUC score of this model is

0.6022374598849909


In [43]:
df = pd.read_excel('testing2.xlsx')
df.drop('Unnamed: 0', axis=1, inplace=True)
model = test_model4_notext(df,'spam_hijack')


Score summary for initial test (first 80% of data)


Accuracy score of this model is

0.905

Log-Loss score of this model is

0.19883826600468407

AUC score of this model is

0.884958984709117



Score summary for final test (last 20% of data)


Accuracy score of this model is

0.905392262166058

Log-Loss score of this model is

0.2046275543500637

AUC score of this model is

0.883971083014124


In [44]:
df = pd.read_excel('testing2.xlsx')
df.drop('Unnamed: 0', axis=1, inplace=True)
processing_text(df,'text')
col_name_lst1 = vectorize_text(df,700)
processing_text(df,'description')
col_name_lst2 = vectorize_desc(df,700)
model = test_model4(df,'spam_hijack',[col_name_lst1+col_name_lst2])


Score summary for initial test (first 80% of data)


Accuracy score of this model is

0.905

Log-Loss score of this model is

0.20717610307263845

AUC score of this model is

0.8858491910164623



Score summary for final test (last 20% of data)


Accuracy score of this model is

0.8998997512461043

Log-Loss score of this model is

0.20798073105550513

AUC score of this model is

0.8770400466377197


In [45]:
df = pd.read_excel('testing2.xlsx')
df.drop('Unnamed: 0', axis=1, inplace=True)
processing_text(df,'text')
col_name_lst1 = vectorize_text(df,100)
processing_text(df,'description')
col_name_lst2 = vectorize_desc(df,100)
model = test_model4(df,'spam_hijack',[col_name_lst1+col_name_lst2])


Score summary for initial test (first 80% of data)


Accuracy score of this model is

0.9065

Log-Loss score of this model is

0.20546445325851023

AUC score of this model is

0.8852625737462698



Score summary for final test (last 20% of data)


Accuracy score of this model is

0.8844243946936652

Log-Loss score of this model is

0.22264537692690595

AUC score of this model is

0.8577221530201606


In [2]:
df = pd.read_excel('testing2.xlsx')
df.drop('Unnamed: 0', axis=1, inplace=True)
processing_text(df,'text')
col_name_lst1 = vectorize_text(df,700)
processing_text(df,'description')
col_name_lst2 = vectorize_desc(df,700)
model1 = test_model4(df,'spam_bot',col_name_lst1+col_name_lst2)


Score summary for initial test (first 80% of data)


Accuracy score of this model is

0.9998750000000001

Log-Loss score of this model is

0.003092100597794022

AUC score of this model is

0.9998955067920585



Score summary for final test (last 20% of data)


Accuracy score of this model is

0.9987521832123811

Log-Loss score of this model is

0.007662978990518721

AUC score of this model is

0.9988556892816469


In [3]:
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification

In [19]:
importances1 = model1.feature_importances_

In [20]:
importances1

array([6.71309691e-02, 4.70280082e-03, 2.89095526e-03, ...,
       3.97073531e-05, 3.45981934e-04, 3.50271232e-06])

In [21]:
ordered_importances1 = np.argsort(importances1)[::-1]

In [22]:
ordered_importances1[:10]

array([183,  78, 673,   3, 151,   0, 207,   4,   7,   5])

In [23]:
importances1[3]

0.10106304354651631

In [24]:
columns = ['Docusign', 'onespan', 'signnow','adobe sign','listed_count', 'statuses_count','followers_count','favourites_count', 'friends_count','time_float_sin','time_float_cos', 'is_description_none']

In [26]:
print(columns[3])
print(columns[0])
print(columns[4])
print(columns[7])
print(columns[5])

adobe sign
Docusign
listed_count
favourites_count
statuses_count


In [27]:
df = pd.read_excel('testing2.xlsx')
df.drop('Unnamed: 0', axis=1, inplace=True)
processing_text(df,'text')
col_name_lst1 = vectorize_text(df,700)
processing_text(df,'description')
col_name_lst2 = vectorize_desc(df,700)
model2 = test_model4(df,'spam_corporate',col_name_lst1+col_name_lst2)


Score summary for initial test (first 80% of data)


Accuracy score of this model is

0.9978125

Log-Loss score of this model is

0.00730198551077333

AUC score of this model is

0.9871231088396126



Score summary for final test (last 20% of data)


Accuracy score of this model is

0.997254055871557

Log-Loss score of this model is

0.017310543475745167

AUC score of this model is

0.9834503099253504


In [28]:
importances2 = model2.feature_importances_
ordered_importances2 = np.argsort(importances2)[::-1]
print(ordered_importances2[:10])

[   6  903 1358 1147  759 1350 1002    8  749 1051]


In [29]:
print(columns[6])
print(columns[8])

followers_count
friends_count


In [30]:
df = pd.read_excel('testing2.xlsx')
df.drop('Unnamed: 0', axis=1, inplace=True)
processing_text(df,'text')
col_name_lst1 = vectorize_text(df,700)
processing_text(df,'description')
col_name_lst2 = vectorize_desc(df,700)
model3 = test_model4(df,'spam_hijack',col_name_lst1+col_name_lst2)


Score summary for initial test (first 80% of data)


Accuracy score of this model is

0.9315

Log-Loss score of this model is

0.1491869620161151

AUC score of this model is

0.9198086426345913



Score summary for final test (last 20% of data)


Accuracy score of this model is

0.9078807351160176

Log-Loss score of this model is

0.17335343793716218

AUC score of this model is

0.904031525897957


In [31]:
importances3 = model3.feature_importances_
ordered_importances3 = np.argsort(importances3)[::-1]
print(ordered_importances3[:10])

[673  78   3 207 183 151   0   5   7   6]


In [34]:
print(columns[3])
print(columns[0])
print(columns[5])
print(columns[7])
print(columns[6])

adobe sign
Docusign
statuses_count
favourites_count
followers_count


In [32]:
df = pd.read_excel('testing2.xlsx')
df.drop('Unnamed: 0', axis=1, inplace=True)
processing_text(df,'text')
col_name_lst1 = vectorize_text(df,700)
processing_text(df,'description')
col_name_lst2 = vectorize_desc(df,700)
model4 = test_model4(df,'spam_marketing',col_name_lst1+col_name_lst2)


Score summary for initial test (first 80% of data)


Accuracy score of this model is

0.9570000000000001

Log-Loss score of this model is

0.11444542820988637

AUC score of this model is

0.696277571427081



Score summary for final test (last 20% of data)


Accuracy score of this model is

0.9505758076718316

Log-Loss score of this model is

0.13040259286901446

AUC score of this model is

0.6282588926768036


In [33]:
importances4 = model4.feature_importances_
ordered_importances4 = np.argsort(importances4)[::-1]
print(ordered_importances4[:10])

[ 10   9   5   6   4   7 673  78   8 207]


In [35]:
print(columns[10])
print(columns[9])
print(columns[5])
print(columns[6])
print(columns[4])
print(columns[7])
print(columns[8])

time_float_cos
time_float_sin
statuses_count
followers_count
listed_count
favourites_count
friends_count
