# Final Check

importing functions

In [1]:
import pandas as pd
import numpy as np

from src.language_processing2 import processing_text
from src.language_processing2 import vectorize_text2
from src.language_processing2 import vectorize_desc2

from src.modeling import test_model4b

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import log_loss
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split,KFold

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [2]:
columns = ['Docusign', 'onespan', 'signnow','adobe sign','listed_count', 'statuses_count','followers_count','favourites_count', 'friends_count','time_float_sin','time_float_cos', 'is_description_none']

In [3]:
df = pd.read_excel('testing2.xlsx')
df.drop('Unnamed: 0', axis=1, inplace=True)
processing_text(df,'text')
col_name_lst1,text_vectorizer = vectorize_text2(df,700)
processing_text(df,'description')
col_name_lst2,desc_vectorizer = vectorize_desc2(df,700)
model1 = test_model4b(df,'spam_bot',col_name_lst1+col_name_lst2)


Score summary for initial test (first 80% of data)


Accuracy score of this model is

0.9999166666666668

Log-Loss score of this model is

0.003759522612045471

AUC score of this model is

0.9999292786421499



Score summary for final test (last 20% of data)


Accuracy score of this model is

1.0

Log-Loss score of this model is

0.003221866971232269

AUC score of this model is

1.0

Score summary for final test (last 20% of data)


Accuracy score of this model is

1.0

Log-Loss score of this model is

0.0026846088808065126

AUC score of this model is

1.0


In [4]:
df = pd.read_excel('testing2.xlsx')
df.drop('Unnamed: 0', axis=1, inplace=True)
processing_text(df,'text')
col_name_lst1,text_vectorizer = vectorize_text2(df,700)
processing_text(df,'description')
col_name_lst2,desc_vectorizer = vectorize_desc2(df,700)

In [13]:
y = df['spam_bot']
X = df[['Docusign', 'onespan', 'signnow','adobe sign','listed_count', 'statuses_count','followers_count','favourites_count', 'friends_count','time_float_sin','time_float_cos', 'is_description_none'] + col_name_lst1+col_name_lst2]
y_pred1 = model1.predict_proba(X)

In [29]:
y_pred1[0]

array([0., 1.])

In [7]:
importances1 = model1.feature_importances_
ordered_importances1 = np.argsort(importances1)[::-1]
print("Here are the top 10 important features")
print("\n")
print(ordered_importances1[:10])
print("\n")
feature_columns1 = columns + text_vectorizer.get_feature_names() + desc_vectorizer.get_feature_names()
for n in ordered_importances1[:10]:
    print(feature_columns1[n])

Here are the top 10 important features


[673 151  78   3 183   0 207   4   7 457]


using
closed
adobesign
adobe sign
deal
Docusign
docusign
listed_count
favourites_count
minute


In [15]:
df = pd.read_excel('testing2.xlsx')
df.drop('Unnamed: 0', axis=1, inplace=True)
processing_text(df,'text')
col_name_lst1,text_vectorizer = vectorize_text2(df,700)
processing_text(df,'description')
col_name_lst2,desc_vectorizer = vectorize_desc2(df,700)
model2 = test_model4b(df,'spam_corporate',col_name_lst1+col_name_lst2)


Score summary for initial test (first 80% of data)


Accuracy score of this model is

0.9973333333333333

Log-Loss score of this model is

0.01009331664425315

AUC score of this model is

0.984236977004889



Score summary for final test (last 20% of data)


Accuracy score of this model is

0.998

Log-Loss score of this model is

0.008455380016840644

AUC score of this model is

0.9878787878787878

Score summary for final test (last 20% of data)


Accuracy score of this model is

0.9995007488766849

Log-Loss score of this model is

0.004986063749949715

AUC score of this model is

0.9970588235294118


In [16]:
df = pd.read_excel('testing2.xlsx')
df.drop('Unnamed: 0', axis=1, inplace=True)
processing_text(df,'text')
col_name_lst1,text_vectorizer = vectorize_text2(df,700)
processing_text(df,'description')
col_name_lst2,desc_vectorizer = vectorize_desc2(df,700)

In [30]:
y = df['spam_corporate']
X = df[['Docusign', 'onespan', 'signnow','adobe sign','listed_count', 'statuses_count','followers_count','favourites_count', 'friends_count','time_float_sin','time_float_cos', 'is_description_none'] + col_name_lst1+col_name_lst2]
y_pred2 = model2.predict_proba(X)

In [9]:
importances2 = model2.feature_importances_
ordered_importances2 = np.argsort(importances2)[::-1]
print("Here are the top 10 important features")
print("\n")
print(ordered_importances2[:10])
print("\n")
feature_columns2 = columns + text_vectorizer.get_feature_names() + desc_vectorizer.get_feature_names()
for n in ordered_importances2[:10]:
    print(feature_columns1[n])

Here are the top 10 important features


[ 903  759    6 1387  749 1147 1358 1051 1353 1201]


docusign
askdocusign
followers_count
welcome
announcement
official
update
know
twitter
product


In [25]:
df = pd.read_excel('testing2.xlsx')
df.drop('Unnamed: 0', axis=1, inplace=True)
processing_text(df,'text')
col_name_lst1,text_vectorizer = vectorize_text2(df,700)
processing_text(df,'description')
col_name_lst2,desc_vectorizer = vectorize_desc2(df,700)
model3 = test_model4b(df,'spam_hijack',col_name_lst1+col_name_lst2)


Score summary for initial test (first 80% of data)


Accuracy score of this model is

0.9265000000000001

Log-Loss score of this model is

0.15503435581673763

AUC score of this model is

0.9185445413333773



Score summary for final test (last 20% of data)


Accuracy score of this model is

0.926

Log-Loss score of this model is

0.1540497941842396

AUC score of this model is

0.9139129245882659

Score summary for final test (last 20% of data)


Accuracy score of this model is

0.936345481777334

Log-Loss score of this model is

0.1368548168706886

AUC score of this model is

0.9211521305593104


In [26]:
df = pd.read_excel('testing2.xlsx')
df.drop('Unnamed: 0', axis=1, inplace=True)
processing_text(df,'text')
col_name_lst1,text_vectorizer = vectorize_text2(df,700)
processing_text(df,'description')
col_name_lst2,desc_vectorizer = vectorize_desc2(df,700)
y = df['spam_hijack']
X = df[['Docusign', 'onespan', 'signnow','adobe sign','listed_count', 'statuses_count','followers_count','favourites_count', 'friends_count','time_float_sin','time_float_cos', 'is_description_none'] + col_name_lst1+col_name_lst2]
y_pred3 = model3.predict_proba(X)


In [28]:
y_pred3[0]

array([1., 0.])

In [11]:
importances3 = model3.feature_importances_
ordered_importances3 = np.argsort(importances3)[::-1]
print("Here are the top 10 important features")
print("\n")
print(ordered_importances3[:10])
print("\n")
feature_columns3 = columns + text_vectorizer.get_feature_names() + desc_vectorizer.get_feature_names()
for n in ordered_importances3[:10]:
    print(feature_columns3[n])

Here are the top 10 important features


[ 78 673   3   0 207 151 183   5   4   7]


adobesign
using
adobe sign
Docusign
docusign
closed
deal
statuses_count
listed_count
favourites_count


In [31]:
df = pd.read_excel('testing2.xlsx')
df.drop('Unnamed: 0', axis=1, inplace=True)
processing_text(df,'text')
col_name_lst1,text_vectorizer = vectorize_text2(df,700)
processing_text(df,'description')
col_name_lst2,desc_vectorizer = vectorize_desc2(df,700)
model4 = test_model4b(df,'spam_marketing',col_name_lst1+col_name_lst2)


Score summary for initial test (first 80% of data)


Accuracy score of this model is

0.9550833333333333

Log-Loss score of this model is

0.11139531427424887

AUC score of this model is

0.6705115780412425



Score summary for final test (last 20% of data)


Accuracy score of this model is

0.96

Log-Loss score of this model is

0.11461438767359411

AUC score of this model is

0.7182392163804803

Score summary for final test (last 20% of data)


Accuracy score of this model is

0.9558162755866201

Log-Loss score of this model is

0.10999046539011022

AUC score of this model is

0.7097863912036215


In [32]:
df = pd.read_excel('testing2.xlsx')
df.drop('Unnamed: 0', axis=1, inplace=True)
processing_text(df,'text')
col_name_lst1,text_vectorizer = vectorize_text2(df,700)
processing_text(df,'description')
col_name_lst2,desc_vectorizer = vectorize_desc2(df,700)
y = df['spam_marketing']
X = df[['Docusign', 'onespan', 'signnow','adobe sign','listed_count', 'statuses_count','followers_count','favourites_count', 'friends_count','time_float_sin','time_float_cos', 'is_description_none'] + col_name_lst1+col_name_lst2]
y_pred4 = model4.predict_proba(X)
y_pred4[:100]

array([[1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [0.996, 0.004],
       [1.   , 0.   ],
       [0.992, 0.008],
       [0.986, 0.014],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [0.982, 0.018],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1. 

In [13]:
importances4 = model4.feature_importances_
ordered_importances4 = np.argsort(importances4)[::-1]
print("Here are the top 10 important features")
print("\n")
print(ordered_importances4[:10])
print("\n")
feature_columns4 = columns + text_vectorizer.get_feature_names() + desc_vectorizer.get_feature_names()
for n in ordered_importances4[:10]:
    print(feature_columns4[n])

Here are the top 10 important features


[ 10   9   5   7  78   8   6   4 207 686]


time_float_cos
time_float_sin
statuses_count
favourites_count
adobesign
friends_count
followers_count
listed_count
docusign
webinar


In [14]:
df.head()

text  spam  spam_marketing  \
0  just closed a deal in 27 hours using #AdobeSig...     0               0   
1  just closed a deal in 2 days using #AdobeSign ...     0               0   
2  just closed a deal in 2 hours using #AdobeSign...     0               0   
3  just closed a deal in 26 hours using #AdobeSig...     0               0   
4  just closed a deal in 6 days using #AdobeSign ...     0               0   

   spam_hijack  spam_corporate  spam_bot  spam_known  spam_own  Docusign  \
0            0               0         1           0         0     False   
1            0               0         1           0         0     False   
2            0               0         1           0         0     False   
3            0               0         1           0         0     False   
4            0               0         1           0         0     False   

   onespan  ...  desc-TF-IDF-690  desc-TF-IDF-691  desc-TF-IDF-692  \
0    False  ...              0.0              0.0              0.0   
1    False  ...              0.0              0.0              0.0   
2    False  ...              0.0              0.0              0.0   
3    False  ...              0.0              0.0              0.0   
4    False  ...              0.0              0.0              0.0   

  desc-TF-IDF-693  desc-TF-IDF-694  desc-TF-IDF-695  desc-TF-IDF-696  \
0             0.0              0.0              0.0              0.0   
1             0.0              0.0              0.0              0.0   
2             0.0              0.0              0.0              0.0   
3             0.0              0.0              0.0              0.0   
4             0.0              0.0              0.0              0.0   

   desc-TF-IDF-697  desc-TF-IDF-698  desc-TF-IDF-699  
0              0.0              0.0              0.0  
1              0.0              0.0              0.0  
2              0.0              0.0              0.0  
3              0.0              0.0              0.0  
4              0.0              0.0              0.0  

[5 rows x 1422 columns]

In [34]:
df = pd.read_excel('testing2.xlsx')
df.drop('Unnamed: 0', axis=1, inplace=True)

In [35]:
df.head()

text  spam  spam_marketing  \
0  just closed a deal in 27 hours using #AdobeSig...     0               0   
1  just closed a deal in 2 days using #AdobeSign ...     0               0   
2  just closed a deal in 2 hours using #AdobeSign...     0               0   
3  just closed a deal in 26 hours using #AdobeSig...     0               0   
4  just closed a deal in 6 days using #AdobeSign ...     0               0   

   spam_hijack  spam_corporate  spam_bot  spam_known  spam_own  Docusign  \
0            0               0         1           0         0     False   
1            0               0         1           0         0     False   
2            0               0         1           0         0     False   
3            0               0         1           0         0     False   
4            0               0         1           0         0     False   

   onespan  ...  adobe sign  listed_count  \
0    False  ...        True             1   
1    False  ...        True            14   
2    False  ...        True             0   
3    False  ...        True             2   
4    False  ...        True             8   

                                         description statuses_count  \
0  There's no substitute for experience! Call 609...           6750   
1  We provide an affordable way to have a wonderf...           5018   
2                                                NaN             29   
3                                                NaN           5332   
4  Carefully Crafted & Intentionally Inspired Eve...           1337   

   followers_count  favourites_count  friends_count  time_float_sin  \
0              108                 1             12       -0.049140   
1               47                 2             25       -0.501007   
2               60                10             52       -0.599548   
3               66                 0            182       -0.325843   
4              225                19            348       -0.098162   

   time_float_cos  is_description_none  
0        0.998792                False  
1        0.865443                False  
2        0.800339                 True  
3        0.945424                 True  
4        0.995170                False  

[5 rows x 21 columns]

In [46]:
df['bot_prob'] = y_pred1[:,1]

In [47]:
df.head()

text  spam  spam_marketing  \
0  just closed a deal in 27 hours using #AdobeSig...     0               0   
1  just closed a deal in 2 days using #AdobeSign ...     0               0   
2  just closed a deal in 2 hours using #AdobeSign...     0               0   
3  just closed a deal in 26 hours using #AdobeSig...     0               0   
4  just closed a deal in 6 days using #AdobeSign ...     0               0   

   spam_hijack  spam_corporate  spam_bot  spam_known  spam_own  Docusign  \
0            0               0         1           0         0     False   
1            0               0         1           0         0     False   
2            0               0         1           0         0     False   
3            0               0         1           0         0     False   
4            0               0         1           0         0     False   

   onespan  ...  listed_count  \
0    False  ...             1   
1    False  ...            14   
2    False  ...             0   
3    False  ...             2   
4    False  ...             8   

                                         description  statuses_count  \
0  There's no substitute for experience! Call 609...            6750   
1  We provide an affordable way to have a wonderf...            5018   
2                                                NaN              29   
3                                                NaN            5332   
4  Carefully Crafted & Intentionally Inspired Eve...            1337   

  followers_count  favourites_count  friends_count  time_float_sin  \
0             108                 1             12       -0.049140   
1              47                 2             25       -0.501007   
2              60                10             52       -0.599548   
3              66                 0            182       -0.325843   
4             225                19            348       -0.098162   

   time_float_cos  is_description_none  bot_prob  
0        0.998792                False       1.0  
1        0.865443                False       1.0  
2        0.800339                 True       1.0  
3        0.945424                 True       1.0  
4        0.995170                False       1.0  

[5 rows x 22 columns]

In [48]:
df['corporate_prob'] = y_pred2[:,1]

In [49]:
df['hijack_prob'] = y_pred3[:,1]

In [50]:
df['marketing_prob'] = y_pred4[:,1]

In [52]:
df.tail(50)

text  spam  \
19956  Do you have a husband &amp; wife signing a doc...     0   
19957  You don't necessarily need IT if you want to f...     0   
19958  Do you know how to check the document and paym...     0   
19959  Share your favorite service with friends/colle...     0   
19960  Protect your #data &amp; combat #cyberattacks ...     0   
19961  Improve operation processes within your compan...     0   
19962  @atharkhan @HelloSign @G2Crowd @RightSignature...     0   
19963  Do you know how to brand your SignNow account ...     0   
19964  #Breaking #Tell this Mayor John A McDonald mus...     0   
19965  Are you a small business looking to streamline...     0   
19966  What eSignature solution should you be signing...     0   
19967  Did you know you can earn up to $300 when you ...     0   
19968  The #SignNow payoff is amplifying your #NetSui...     0   
19969  SignNow lets you provide additional services i...     0   
19970  Looking to streamline your document workflow? ...     0   
19971  Technology is evolving in the #healthcare indu...     0   
19972  We love referrals! Make extra money this #summ...     0   
19973  @signnow When will your service be back up? Ge...     0   
19974  #SignNow allows you to redline, edit, redact, ...     0   
19975  Did you know health plans and #healthcare prov...     0   
19976  SignNow rescues your company from the unnecess...     0   
19977  If you send out 1000 docs for HR/Comp signing,...     0   
19978  Extend that last mile with a one-way or two-wa...     0   
19979  SignNow helps put the puzzle pieces together f...     0   
19980  With #SignNow, you are flexible enough to chan...     0   
19981  Do you want a digital interactive &amp; engagi...     0   
19982  @atharkhan @HelloSign @G2Crowd @RightSignature...     0   
19983  Are you looking to make ACH Payments using Str...     0   
19984  5 major benefits of choosing SignNow for #medi...     0   
19985  Do you need to send a document to a group of p...     0   
19986  @beezy It should be back up. It was down for a...     0   
19987  #Didyouknow that you can create a link to put ...     0   
19988  SignNow helps get patient forms signed faster ...     0   
19989  You probably knew that you can save money with...     0   
19990  Need to sign last minute #legal forms? SignNow...     0   
19991  @claaack Hi Mr. November, I apologize. We are ...     0   
19992  and sign the petition as it needs lots &amp; l...     0   
19993  Using an Electronic Signature or E-Signature a...     0   
19994  #LaborDay Weekend yet? Don't let work hold you...     0   
19995  Are you having an event for your office for th...     0   
19996  Summer is fading but the dollars in your bank ...     0   
19997  Do you need to sign documents in person on an ...     0   
19998  Are you stressed about getting a document sign...     0   
19999  Please join in the effort to stop genocide in ...     0   
20000  @Anafa It should be back up. It was down for a...     0   
20001  @signnow Yes, they apologized for the issues b...     0   
20002  SignNow ensures that you cannot be breached by...     0   
20003  @claaack Hi Mr. November, Were you able to get...     0   
20004  Want extra money this #LaborDay weekend withou...     0   
20005  Are you in #HR? Save yourself time on reusable...     0   

       spam_marketing  spam_hijack  spam_corporate  spam_bot  spam_known  \
19956               0            0               1         0           0   
19957               1            0               0         0           0   
19958               0            0               1         0           0   
19959               0            0               1         0           0   
19960               0            0               1         0           0   
19961               0            0               1         0           0   
19962               0            0               1         0           0   
19963               0            0               1         0           0   
1

In [53]:
df.to_excel("website_display.xlsx",sheet_name='Sheet_name_1') 

In [5]:
df = pd.read_excel("website_display.xlsx")

In [6]:
df.iloc[16000:17000]

index                                               text  spam  \
16000  16000  Wrapping up a great Opening Reception at @Docu...     0   
16001  16001  🗞️ DocuSign CEO: ‘we’re becoming a ve...     0   
16002  16002  Frustrating how many companies won't accept di...     0   
16003  16003  What is @DocuSign Payments? How do you get you...     0   
16004  16004  #phishing target: @DocuSign\nURL: hxxps://docu...     0   
16005  16005  @DocuSign you guys should make the login butto...     0   
16006  16006  Retweeted BitPay (@BitPay):\n\nWe're joining @...     0   
16007  16007  Not sure what to make out of the #eIDAS regula...     0   
16008  16008  ICYMI -- We've joined the Chamber of Digital C...     0   
16009  16009  What’s going on at @DocuSign ? Three months ...     0   
16010  16010  How to Use DocuSign to Digitally Sign Document...     0   
16011  16011  Join Girls in Tech SF and #HackforHumanity at ...     0   
16012  16012  We’re all set up at @DocuSign #Momentum18. M...     0   
16013  16013  Use eSignature to Streamline Your Business .@s...     0   
16014  16014  With new local data centres and plans to incre...     0   
16015  16015  DocuSign Phishing Scam – How to Get Rid of i...     0   
16016  16016  Do you have the right tools for creating and m...     0   
16017  16017  Then hour later a different visitor returns fr...     0   
16018  16018  ATTENTION! DocuSign has observed a new phishin...     0   
16019  16019  How Docusign Works For People Selling A Home O...     0   
16020  16020  Join Girls in Tech SF and #HackforHumanity at ...     0   
16021  16021  RT Greetly "Use eSignature to Streamline Your ...     0   
16022  16022  Great seeing @JeffreyHayzlett and @KeithJKrach...     0   
16023  16023  Use eSignature to Streamline Your Business .@s...     0   
16024  16024  DocuSign: Women in Tech at DocuSign: Jen Z. - ...     0   
16025  16025  Last night at the @DocuSign real estate dinner...     0   
16026  16026  .@DocuSign #Phishing for @Outlook @Office365 @...     0   
16027  16027  Prepare. \nSign. \nAct.\nManage. \n\nWe're mod...     0   
16028  16028  trickbot. Docusign lure, Gtag ser0719us @James...     0   
16029  16029  Use eSignature to Streamline Your Business .@s...     0   
...      ...                                                ...   ...   
16970  16970  Oh, baby! I can't wait for @DocuSign to acquir...     0   
16971  16971  @mdudas @TheBlock__ @WeWork @JustworksHR @gsui...     0   
16972  16972  EPS for DocuSign, Inc. $DOCU Expected At $-0.1...     0   
16973  16973  Check out My Gigs on #Fiverr https://t.co/F2mZ...     0   
16974  16974  @bensprecher @mdudas @TheBlock__ @WeWork @Just...     0   
16975  16975  EPS for DocuSign, Inc. $DOCU Expected At $-0.1...     0   
16976  16976  #askhalftime Anyone own or have an opinion on ...     0   
16977  16977  EPS for DocuSign, Inc. $DOCU Expected At $-0.1...     0   
16978  16978  Have you checked out the @procoretech integrat...     0   
16979  16979  UK SMB Sales Manager: DocuSign - Dublin - For ...     0   
16980  16980  EPS for DocuSign, Inc. $DOCU Expected At $-0.1...     0   
16981  16981  Cien was ranked one the fastest growing #SaaS ...     0   
16982  16982  @hnjsamuels @eabanter Cleaner to all sign the ...     0   
16983  16983  @CGregoryBrown @pgarg @DocuSign What a complim...     0   
16984  16984  DocuSign and Workday: The Story from US Acute ...     0   
16985  16985      Can't blame on DocuSign but it's new process.     0   
16986  16986  Release notes. Building single-page apps with ...     0   
16987  16987  More Canadian mobile telecom based phishing us...     0   
16988  16988  @mdudas @TheBlock__ @WeWork @JustworksHR @gsui...     0   
16989  16989  @anxiousadvisor @DocuSign Yeah, I think they t...     0   
16990  16990  Keep your business moving forward at lightning...     0   
16991  16991  In case you were at #GoogleNEXT18 and want to ...     0   
16992  16992  Wow, I just got my first electronic signature ...  

In [7]:
0
16002
16006
19993

19993

In [9]:
df.iloc[0]

index                                                                  0
text                   just closed a deal in 27 hours using #AdobeSig...
spam                                                                   0
spam_marketing                                                         0
spam_hijack                                                            0
spam_corporate                                                         0
spam_bot                                                               1
spam_known                                                             0
spam_own                                                               0
Docusign                                                               0
onespan                                                                0
signnow                                                                0
adobe sign                                                             1
listed_count                                       

In [60]:
def row_info(x):
    df = pd.read_excel("website_display.xlsx")
    text = "Tweet Post: " + df['text'][x] + "\n\n" + "Description: " + str(df['description'][x]) + "\n"
    
    stats = "\n" + "Followers: " + str(df['followers_count'][x]) + "\n" + "Favourites: " + str(df['favourites_count'][x]) + "\n" + "Statuses: " + str(df['statuses_count'][x]) + "\n"
    
    prob1 = "\n"+ "probability of bot generated: " + "{percent:.2%}".format(percent=df['bot_prob'][x])
    prob2 = "\n"+"probability of corporate posted: " + "{percent:.2%}".format(percent=df['corporate_prob'][x])
    prob3 = "\n"+"probability of hijacking keywords: " + "{percent:.2%}".format(percent=df['hijack_prob'][x])
    prob4 = "\n"+"probability of marketing spam: " + "{percent:.2%}".format(percent=df['marketing_prob'][x])
    return text+stats+prob1+prob2+prob3+prob4

In [10]:
df['text'][0]

'just closed a deal in 27 hours using #AdobeSign https://t.co/Fe0YfarG31'

In [51]:
print(row_info(6))

Tweet Post: just closed a deal in 3 days using #AdobeSign https://t.co/su9NFDvRSm
Description: SP Guard from Iconix uses enhancements to standards-based authentication to defend enterprises from spearphishing.

Followers: 161
Favourites: 0
Statuses: 419

probability of bot generated: 99.80%
probability of corporate posted: 0.20%
probability of hijacking keywords: 0.00%
probability of marketing spam: 0.40%


In [52]:
0
16002
16006
19993

19993

In [53]:
print(row_info(0))

Tweet Post: just closed a deal in 27 hours using #AdobeSign https://t.co/Fe0YfarG31
Description: There's no substitute for experience! Call 609-402-8900 today and experience the Island Realty Group difference!

Followers: 108
Favourites: 1
Statuses: 6750

probability of bot generated: 100.00%
probability of corporate posted: 0.00%
probability of hijacking keywords: 0.00%
probability of marketing spam: 0.00%


In [56]:
print(row_info(16002))

Tweet Post: Frustrating how many companies won't accept digital signatures like @DocuSign in 2018. If anything, it's far more secure than a handwritten signature that *could* be anyone's writing.

Description: Co-founder & Creative Director @unrd. We're shaking things up on your 📱 Check out our award-winning first story @LastSeenOnline 🥇views my own.

Followers: 5313
Favourites: 2397
Statuses: 11259

probability of bot generated: 0.20%
probability of corporate posted: 0.40%
probability of hijacking keywords: 14.80%
probability of marketing spam: 7.40%


In [58]:
print(row_info(16002))

Tweet Post: Frustrating how many companies won't accept digital signatures like @DocuSign in 2018. If anything, it's far more secure than a handwritten signature that *could* be anyone's writing.

Description: Co-founder & Creative Director @unrd. We're shaking things up on your 📱 Check out our award-winning first story @LastSeenOnline 🥇views my own.

Followers: 5313
Favourites: 2397
Statuses: 11259

probability of bot generated: 0.20%
probability of corporate posted: 0.40%
probability of hijacking keywords: 14.80%
probability of marketing spam: 7.40%


In [62]:
print(row_info(16006))

Tweet Post: Retweeted BitPay (@BitPay):

We're joining @DocuSign, @civickey, and others on the Executive Committee of the #blockchain industry's largest trade organization, @DigitalChamber: https://t.co/ZeGGtaP3Yt #Fintech

Description: nan

Followers: 250
Favourites: 1281
Statuses: 42790

probability of bot generated: 0.00%
probability of corporate posted: 0.60%
probability of hijacking keywords: 85.00%
probability of marketing spam: 1.20%


In [63]:
print(row_info(19993))

Tweet Post: Using an Electronic Signature or E-Signature as a form of authentication has become a necessary tool in digitizing business. Read our take on Top E-signing tools. @HelloSign @DocuSign @signnow @RightSignature @getsigneasy @OneSpanSign and @adobe Signs,
https://t.co/K15XXjFrOP https://t.co/zfjSNutCqG

Description: nan

Followers: 73
Favourites: 103
Statuses: 167

probability of bot generated: 0.00%
probability of corporate posted: 0.20%
probability of hijacking keywords: 64.75%
probability of marketing spam: 87.20%
