# Final Check

importing functions

In [1]:
import pandas as pd
import numpy as np

from src.language_processing2 import processing_text
from src.language_processing2 import vectorize_text2
from src.language_processing2 import vectorize_desc2

from src.modeling import test_model4b

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import log_loss
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split,KFold

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [3]:
columns = ['Docusign', 'onespan', 'signnow','adobe sign','listed_count', 'statuses_count','followers_count','favourites_count', 'friends_count','time_float_sin','time_float_cos', 'is_description_none']

In [2]:
df = pd.read_excel('testing2.xlsx')
df.drop('Unnamed: 0', axis=1, inplace=True)
processing_text(df,'text')
col_name_lst1,text_vectorizer = vectorize_text2(df,700)
processing_text(df,'description')
col_name_lst2,desc_vectorizer = vectorize_desc2(df,700)
model1 = test_model4b(df,'spam_bot',col_name_lst1+col_name_lst2)


Score summary for initial test (first 80% of data)


Accuracy score of this model is

0.9996666666666666

Log-Loss score of this model is

0.0036907481970301264

AUC score of this model is

0.9997056659308315



Score summary for final test (last 20% of data)


Accuracy score of this model is

1.0

Log-Loss score of this model is

0.0036964742920723363

AUC score of this model is

1.0

Score summary for final test (last 20% of data)


Accuracy score of this model is

1.0

Log-Loss score of this model is

0.002934668711336333

AUC score of this model is

1.0


In [7]:
importances1 = model1.feature_importances_
ordered_importances1 = np.argsort(importances1)[::-1]
print("Here are the top 10 important features")
print("\n")
print(ordered_importances1[:10])
print("\n")
feature_columns1 = columns + text_vectorizer.get_feature_names() + desc_vectorizer.get_feature_names()
for n in ordered_importances1[:10]:
    print(feature_columns1[n])

Here are the top 10 important features


[673 151  78   3 183   0 207   4   7 457]


using
closed
adobesign
adobe sign
deal
Docusign
docusign
listed_count
favourites_count
minute


In [8]:
df = pd.read_excel('testing2.xlsx')
df.drop('Unnamed: 0', axis=1, inplace=True)
processing_text(df,'text')
col_name_lst1,text_vectorizer = vectorize_text2(df,700)
processing_text(df,'description')
col_name_lst2,desc_vectorizer = vectorize_desc2(df,700)
model2 = test_model4b(df,'spam_corporate',col_name_lst1+col_name_lst2)


Score summary for initial test (first 80% of data)


Accuracy score of this model is

0.9974999999999999

Log-Loss score of this model is

0.01241449643572887

AUC score of this model is

0.9848528958238365



Score summary for final test (last 20% of data)


Accuracy score of this model is

0.99825

Log-Loss score of this model is

0.006255295325945092

AUC score of this model is

0.9894894894894894

Score summary for final test (last 20% of data)


Accuracy score of this model is

0.9980029955067399

Log-Loss score of this model is

0.006843248582033045

AUC score of this model is

0.988795518207283


In [9]:
importances2 = model2.feature_importances_
ordered_importances2 = np.argsort(importances2)[::-1]
print("Here are the top 10 important features")
print("\n")
print(ordered_importances2[:10])
print("\n")
feature_columns2 = columns + text_vectorizer.get_feature_names() + desc_vectorizer.get_feature_names()
for n in ordered_importances2[:10]:
    print(feature_columns1[n])

Here are the top 10 important features


[ 903  759    6 1387  749 1147 1358 1051 1353 1201]


docusign
askdocusign
followers_count
welcome
announcement
official
update
know
twitter
product


In [10]:
df = pd.read_excel('testing2.xlsx')
df.drop('Unnamed: 0', axis=1, inplace=True)
processing_text(df,'text')
col_name_lst1,text_vectorizer = vectorize_text2(df,700)
processing_text(df,'description')
col_name_lst2,desc_vectorizer = vectorize_desc2(df,700)
model3 = test_model4b(df,'spam_hijack',col_name_lst1+col_name_lst2)


Score summary for initial test (first 80% of data)


Accuracy score of this model is

0.9240833333333333

Log-Loss score of this model is

0.15222700859366337

AUC score of this model is

0.9137023414019427



Score summary for final test (last 20% of data)


Accuracy score of this model is

0.9265

Log-Loss score of this model is

0.1549414174202167

AUC score of this model is

0.9147779546637937

Score summary for final test (last 20% of data)


Accuracy score of this model is

0.9345981028457314

Log-Loss score of this model is

0.14122389072100308

AUC score of this model is

0.9230427225916257


In [11]:
importances3 = model3.feature_importances_
ordered_importances3 = np.argsort(importances3)[::-1]
print("Here are the top 10 important features")
print("\n")
print(ordered_importances3[:10])
print("\n")
feature_columns3 = columns + text_vectorizer.get_feature_names() + desc_vectorizer.get_feature_names()
for n in ordered_importances3[:10]:
    print(feature_columns3[n])

Here are the top 10 important features


[ 78 673   3   0 207 151 183   5   4   7]


adobesign
using
adobe sign
Docusign
docusign
closed
deal
statuses_count
listed_count
favourites_count


In [12]:
df = pd.read_excel('testing2.xlsx')
df.drop('Unnamed: 0', axis=1, inplace=True)
processing_text(df,'text')
col_name_lst1,text_vectorizer = vectorize_text2(df,700)
processing_text(df,'description')
col_name_lst2,desc_vectorizer = vectorize_desc2(df,700)
model4 = test_model4b(df,'spam_marketing',col_name_lst1+col_name_lst2)


Score summary for initial test (first 80% of data)


Accuracy score of this model is

0.9555

Log-Loss score of this model is

0.11458119863570496

AUC score of this model is

0.6893521367956407



Score summary for final test (last 20% of data)


Accuracy score of this model is

0.94975

Log-Loss score of this model is

0.1139981611342206

AUC score of this model is

0.6801333333333333

Score summary for final test (last 20% of data)


Accuracy score of this model is

0.9623065401897154

Log-Loss score of this model is

0.09835395583682799

AUC score of this model is

0.7077092799085476


In [13]:
importances4 = model4.feature_importances_
ordered_importances4 = np.argsort(importances4)[::-1]
print("Here are the top 10 important features")
print("\n")
print(ordered_importances4[:10])
print("\n")
feature_columns4 = columns + text_vectorizer.get_feature_names() + desc_vectorizer.get_feature_names()
for n in ordered_importances4[:10]:
    print(feature_columns4[n])

Here are the top 10 important features


[ 10   9   5   7  78   8   6   4 207 686]


time_float_cos
time_float_sin
statuses_count
favourites_count
adobesign
friends_count
followers_count
listed_count
docusign
webinar
